### PR TITLE
Resolve `test_approx` ambiguities

### LINKED ISSUE #252: `test_approx` ambiguities
Found in the wild here: https://github.com/JuliaDiff/ChainRules.jl/pull/642#discussion_r915406061

And some similar test cases that fail:
```julia
test_approx(
    @thunk(Tangent{Tuple{Float64,Float64}}(1.0, 2.0)),
    Tangent{Tuple{Float64,Float64}}(1.0, 2.0),
)

test_approx(@thunk(ZeroTangent()), ZeroTangent())

test_approx(ZeroTangent(), @thunk(ZeroTangent()))

test_approx(
    Tangent{Tuple{Float64,Float64}}(ZeroTangent(), NoTangent()),
    NoTangent(),
)

test_approx(
    NoTangent(),
    Tangent{Tuple{Float64,Float64}}(ZeroTangent(), NoTangent()),
)
```

### PR DESCRIPTION
**Pull request by mzgubic**
Closes #252

### CODE REVIEW

File: test/check_result.jl [hunk 1]
```diff
@@ -83,6 +83,20 @@ end
                 Tangent{Tuple{Float64,Float64}}(1.0, 2.0),
                 @thunk(Tangent{Tuple{Float64,Float64}}(1.0, 2.0)),
             )
+            test_approx(
+                @thunk(Tangent{Tuple{Float64,Float64}}(1.0, 2.0)),
+                Tangent{Tuple{Float64,Float64}}(1.0, 2.0),
+            )
+            test_approx(@thunk(ZeroTangent()), ZeroTangent())
+            test_approx(ZeroTangent(), @thunk(ZeroTangent()))
+            test_approx(
```
Comment (mzgubic) [inline test/check_result.jl:92]: Do we want this? I think we do?

File: test/check_result.jl [hunk 2]
```diff
@@ -83,6 +83,20 @@ end
...
+                Tangent{Tuple{Float64,Float64}}(ZeroTangent(), NoTangent()),
+                NoTangent(),
+            )
+            test_approx(
+                NoTangent(),
+                Tangent{Tuple{Float64,Float64}}(ZeroTangent(), NoTangent()),
+            )
```
Comment (mzgubic) [inline test/check_result.jl:99]: Do we want this? I think we do

**Review by oxinabox — APPROVED** [review]

**Comment by mcabbott** [comment]
Fixes the example from #229 too:
```
julia> ChainRulesTestUtils.test_approx(Tangent{Int}(; x=1), ZeroTangent())
false

(jl_rp9LKs) pkg> st
Status `/private/var/folders/yq/4p2zwd614y59gszh7y9ypyhh0000gn/T/jl_rp9LKs/Project.toml`
  [cdddcdb0] ChainRulesTestUtils v1.8.2 `https://github.com/JuliaDiff/ChainRulesTestUtils.jl#mz/testapprox`
```

File: test/check_result.jl (hunk 2 above)
Comment (mzgubic) [reply test/check_result.jl]: In practice I think what matters is that `NoTangent()` is the same as `Tangent` of just `NoTangent()`s.

E.g. the choice similar to the one we made in
```julia
julia> rand_tangent((1, 2))
NoTangent()
```

I added on the `ZeroTangent` on purely practical grounds, since they are effectively the same. But I can't justify it either, so we can push that decision down the road when we deal with automating testing a bit better, and restrict to `NoTangent` for now.

Does that sound good to merge?

Comment (oxinabox) [reply test/check_result.jl]: That sounds good
