### PR TITLE
Better error message when user accidentally passes `Zero()` instead of `DoesNotExist()` in the pullback

### LINKED ISSUE #112: Error message to explain that non differentiable arguments should be marked as DoesNotExist(), not Zero()
Currently, if someone mistakenly uses `Zero()` instead of `DoesNotExist()` inside the `rrule`
```julia
function partly_dne(a, i)
    return a[i]
end

function ChainRulesCore.rrule(::typeof(partly_dne), a, i)
    y = partly_dne(a, i)
    function partly_dne_pullback(ȳ)
        grad = zeros(size(a))
        grad[i] = ȳ
        return (NO_FIELDS, grad, Zero())
    end
    return y, partly_dne_pullback
end
```
The error message isn't very clear
```julia
julia> rrule_test(partly_dne, rand(), (rand(4), rand(4)), (1, nothing))
Test Failed at /Users/mzgubic/Projects/ChainRules.jl/dev/ChainRulesTestUtils/src/testers.jl:295
  Expression: x̄_ad isa DoesNotExist
   Evaluated: Zero() isa DoesNotExist
ERROR: There was an error during testing
```

### PR DESCRIPTION
**Pull request by mzgubic**
Closes #112 

I don't think we need a test for this?

### CODE REVIEW

File: src/testers.jl [hunk 1]
```diff
@@ -205,6 +205,10 @@ function test_rrule(
         for (accumulated_x̄, x̄_ad, x̄_fd) in zip(accumulated_x̄, x̄s_ad, x̄s_fd)
             if accumulated_x̄ isa Union{Nothing, DoesNotExist}  # then we marked this argument as not differentiable # TODO remove once #113
                 @assert x̄_fd === nothing  # this is how `_make_j′vp_call` works
+                x̄_ad isa Zero && error(
+                    "The pullback in the rrule for $f function should use DoesNotExist()" *
+                    " rather than Zero() for non-differentiable arguments."
```
Comment (oxinabox) [inline src/testers.jl:210]: I kind of want to say non-perturbable or discretely valued inputs.
Non-differentiable feels to vague, and also lime it is a property primilily of the function rather than the input

**Review by oxinabox — COMMENTED** [review]
I think this does need a test.
Just a `@test_throws`

**Comment by mzgubic** [comment]
> I think this does need a test.
> Just a `@test_throws`

I've tried
```julia
@testset "error message about incorrectly using Zero()" begin
    foo(a, i) = a[i] 
    function ChainRulesCore.rrule(::typeof(foo), a, i)
        function foo_pullback(Δy)
            da = zeros(size(a))
            da[i] = Δy 
            return NO_FIELDS, da, Zero()
        end  
        return foo(a, i), foo_pullback
    end  
    @test_throws Exception test_rrule(foo, [1.0, 2.0, 3.0], 2)
end
```

But that leaves a mess because the exception is thrown inside one of the 5 tests done by `test_rrule`

```julia
test_rrule: foo at ([1.0, 2.0, 3.0], 2): Error During Test at /Users/mzgubic/JuliaEnvs/ChainRulesTestUtils.jl/src/testers.jl:168
  Got exception outside of a @test
  The pullback in the rrule for foo function should use DoesNotExist() rather than Zero() for non-perturbable arguments.
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] macro expansion
      @ ~/JuliaEnvs/ChainRulesTestUtils.jl/src/testers.jl:208 [inlined]
    [3] macro expansion
      @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
    [4] test_rrule(::var"#foo#18", ::Vector{Float64}, ::Vararg{Any, N} where N; output_tangent::ChainRulesTestUtils.Auto, fdm::FiniteDifferences.AdaptedFiniteDifferenceMethod{5, 1, FiniteDifferences.UnadaptedFiniteDifferenceMethod{7, 5}}, check_inferred::Bool, fkwargs::NamedTuple{(), Tuple{}}, rtol::Float64, atol::Float64, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ ChainRulesTestUtils ~/JuliaEnvs/ChainRulesTestUtils.jl/src/testers.jl:169
    [5] test_rrule(::Function, ::Vector{Float64}, ::Vararg{Any, N} where N)
      @ ChainRulesTestUtils ~/JuliaEnvs/ChainRulesTestUtils.jl/src/testers.jl:166
    [6] macro expansion
      @ REPL[34]:11 [inlined]
    [7] macro expansion
      @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
    [8] top-level scope
      @ REPL[34]:2
    [9] eval
      @ ./boot.jl:360 [inlined]
   [10] eval_user_input(ast::Any, backend::REPL.REPLBackend)
      @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
   [11] repl_backend_loop(backend::REPL.REPLBackend)
      @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
   [12] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
      @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
   [13] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
      @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
   [14] run_repl(repl::REPL.AbstractREPL, consumer::Any)
      @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
   [15] (::Base.var"#874#876"{Bool, Bool, Bool})(REPL::Module)
      @ Base ./client.jl:387
   [16] #invokelatest#2
      @ ./essentials.jl:708 [inlined]
   [17] invokelatest
      @ ./essentials.jl:706 [inlined]
   [18] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
      @ Base ./client.jl:372
   [19] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:302
   [20] _start()
      @ Base ./client.jl:485
error message about incorrectly using Zero(): Test Failed at REPL[34]:11
  Expression: test_rrule(foo, [1.0, 2.0, 3.0], 2)
    Expected: Exception
  No exception thrown
Stacktrace:
 [1] macro expansion
   @ REPL[34]:11 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ REPL[34]:2
Test Summary:                                | Pass  Fail  Error  Total
error message about incorrectly using Zero() |    4     1      1      6
  test_rrule: foo at ([1.0, 2.0, 3.0], 2)    |    4            1      5
ERROR: Some tests did not pass: 4 passed, 1 failed, 1 errored, 0 broken.
```

**Comment by oxinabox** [comment]
Ah right, 
yeah you will need to use the `errors()` function from our metatesting tools 
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/8b5e9067cec52cf97da5cceec9bc040460c5cccd/test/meta_testing_tools.jl#L190

Something like
```julia
@test errors("should use DoesNotExist") do
    test_rrule(foo, [1.0, 2.0, 3.0], 2)
end
```

**Review by oxinabox — APPROVED** [review]
